---
title: "match_twins"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#twins2013<-read.csv("~/Desktop/PhD/2021 Spring/STAT 566/project/data/twins2013.csv")
```

```{r}
#procedure proposal
colnames(twins2013)
#combine variables dob_mm, dob_wk, mager41, uprevis, wtgain, cig_1, cig_2, cig_3
  #Note that this could be one limitation in our study since we can't say for sure 100% that we are absolutely right about 
  #the matching. There is still a small prob that there are some moms will have the same values for all those variables.

#mother’s age, state of birth, state of residence, race, and education, marital status of the parents, father’s age, father’s education, and the month in which prenatal care began
twins2013_1<-twins2013%>%mutate(identifier=paste(mager41, restatus, meduc, mracerec, mar, fagerec11, precare, uprevis, cig_1, cig_2, cig_3, dob_mm, dob_wk, fracerec, wtgain, sep=", "))
table(is.na(twins2013_1$identifier))

#see how many unique combinations are there and see if it is approx. half of the obs
length(unique(twins2013_1$identifier)) 

#give the same pairs a unique twin number just to make it computationally easier for later steps
pair_num<-as.data.frame(unique(twins2013_1$identifier))
pair_num$number<-row_number(pair_num)
colnames(pair_num)<-c("identifier", "number")
twins_2013_2<-twins2013_1%>%left_join(pair_num, by="identifier")
table(is.na(twins_2013_2$identifier))

#see how many twins, triplets, quadruplets in our data
#2:132589   3:4392      4:270    5:66
table(twins2013$dplural)
numintwin<-twins_2013_2%>%group_by(number)%>%summarize(n_children=n())
check<-twins_2013_2%>%filter(number%in%numintwin[numintwin$n_children==6 ,1]$number)
twins_2013_3<-twins_2013_2%>%left_join(numintwin, by="number")
table(twins_2013_3$n_children)
twins_2013_nosing<-twins_2013_3%>%filter(n_children!=1)
#unmatched percent
12992/123723
110731/123723

#give birth order and remove those who can't determine
twins_2013_twins<-twins_2013_3%>%filter(n_children==2)
twins_2013_triplets<-twins_2013_3%>%filter(n_children==3)
twins_2013_quad<-twins_2013_3%>%filter(n_children==4)
twins_2013_quin<-twins_2013_3%>%filter(n_children==5)

twins_2013_quin%>%group_by(number)%>%summarise(orderable=length(unique(lbo))==5)
twins_2013_quin_ord<-twins_2013_quin

orderable_quad<-twins_2013_quad%>%group_by(number)%>%summarise(orderable=length(unique(lbo))==4)
table(orderable_quad$orderable)
falsenum<-with(orderable_quad, orderable_quad[orderable==FALSE,]$number)
twins_2013_quad%>%filter(number%in%falsenum)
twins_2013_quad_ord<-twins_2013_quad%>%filter(!(number%in%falsenum))

orderable_trip<-twins_2013_triplets%>%group_by(number)%>%summarise(orderable=length(unique(lbo))==3)
table(orderable_trip$orderable)
falsenum<-with(orderable_trip, orderable_trip[orderable==FALSE,]$number)
twins_2013_triplets%>%filter(number%in%falsenum)
twins_2013_trip_ord<-twins_2013_triplets%>%filter(!(number%in%falsenum))

orderable_twin<-twins_2013_twins%>%group_by(number)%>%summarise(orderable=length(unique(lbo))==2)
table(orderable_twin$orderable)
falsenum<-with(orderable_twin, orderable_twin[orderable==FALSE,]$number)
temp<-twins_2013_twins%>%filter(number%in%falsenum)
twins_2013_twin_ord<-twins_2013_twins%>%filter(!(number%in%falsenum))

#110731 no singletons
nrow(twins_2013_quad_ord)+nrow(twins_2013_quin_ord)+nrow(twins_2013_trip_ord)+nrow(twins_2013_twin_ord)
87363/110731
87363/123723

```



















```{r}
library(tidyverse)
#twins2011<-read.csv("~/Desktop/twins2011.csv")
```

```{r}
#procedure proposal
colnames(twins2011)
#combine variables dob_mm, dob_wk, mager41, uprevis, wtgain, cig_1, cig_2, cig_3
  #Note that this could be one limitation in our study since we can't say for sure 100% that we are absolutely right about 
  #the matching. There is still a small prob that there are some moms will have the same values for all those variables.

#mother’s age, state of birth, state of residence, race, and education, marital status of the parents, father’s age, father’s education, and the month in which prenatal care began
twins2011_1<-twins2011%>%mutate(identifier=paste(mager41, restatus, meduc, mracerec, mar, fagerec11, precare, dplural, uprevis, cig_1, cig_2, cig_3, dob_mm, dob_wk, fracerec, wtgain, sep=", "))
table(is.na(twins2011_1$identifier))

#see how many unique combinations are there and see if it is approx. half of the obs
length(unique(twins2011_1$identifier)) 
46479/123723 #49.1%

#give the same pairs a unique twin number
pair_num1<-as.data.frame(unique(twins2011_1$identifier))
pair_num1$number<-row_number(pair_num1)
colnames(pair_num1)<-c("identifier", "number")
twins_2011_2<-twins2011_1%>%left_join(pair_num1, by="identifier")
table(is.na(twins_2011_2$identifier))

#see how many twins, triplets, quadruplets in our data
#2:132589   3:4392      4:270    5:66
table(twins2011$dplural)
numintwin1<-twins_2011_2%>%group_by(number)%>%summarise(n_children=n())
table(numintwin1$n_children)
check<-twins_2011_2%>%filter(number%in%numintwin1[numintwin1$n_children==1,1]$number)
check$identifier
#use gather/spread to combine the mortality and birth_order and birth weight info





```

